### ISSUE TITLE
fit() got an unexpected keyword argument 'nb_epoch'

### ISSUE THREAD

**Issue by ys7yoo** [ys7yoo/nn_robust_attacks#2]
```
Traceback (most recent call last):
  File "train_models.py", line 109, in <module>
    train(CIFAR(), "models/cifar", [64, 64, 128, 128, 256, 256], num_epochs=50)
  File "train_models.py", line 66, in train
    shuffle=True)
TypeError: fit() got an unexpected keyword argument 'nb_epoch'
```

**Comment by ys7yoo** [comment]
https://github.com/keras-team/keras/issues/14135

**Comment by ys7yoo** [comment]
replaced `nb_epoch` with `epochs`
